exports.config = {
  server: '',
  admob: {
    'ios-assessment-popup': '',
    'ios-vocab-list-popup': '',

    'ios-about-banner': '',
    'ios-assessment-banner': '',
    'ios-assessment-listening-banner': '',
    'ios-assessment-mc-banner': '',
    'ios-kana-banner': '',
    'ios-lessons-banner': '',
    'ios-read-all-banner': '',
    'ios-search-banner': '',
    'ios-select-mode-banner': '',
    'ios-today-banner': '',
    'ios-vocab-list-banner': '',

    'android-assessment-popup': '',
    'android-vocab-list-popup': '',

    'android-about-banner': '',
    'android-assessment-banner': '',
    'android-assessment-listening-banner': '',
    'android-assessment-mc-banner': '',
    'android-kana-banner': '',
    'android-lessons-banner': '',
    'android-read-all-banner': '',
    'android-search-banner': '',
    'android-select-mode-banner': '',
    'android-today-banner': '',
    'android-vocab-list-banner': '',
  },
  onesignal: '',
  segment: '',
  inAppProducts: ['android.test.purchased', 'android.test.item_unavailable'],
  oneskyApiKey: '',
  oneskySecretKey: '',
};
