exports.config = {
  server: '',
  admob: {
    'japanese-ios-popup': '',
    'japanese-ios-about-banner': '',
    'japanese-ios-assessment-banner': '',
    'japanese-ios-kana-banner': '',
    'japanese-ios-lessons-banner': '',
    'japanese-ios-read-all-banner': '',
    'japanese-ios-search-banner': '',
    'japanese-ios-today-banner': '',
    'japanese-ios-vocab-list-banner': '',

    'japanese-android-popup': '',
    'japanese-android-about-banner': '',
    'japanese-android-assessment-banner': '',
    'japanese-android-kana-banner': '',
    'japanese-android-lessons-banner': '',
    'japanese-android-read-all-banner': '',
    'japanese-android-search-banner': '',
    'japanese-android-today-banner': '',
    'japanese-android-vocab-list-banner': '',
  },
  onesignal: '',
  segment: '',
  inAppProducts: ['android.test.purchased', 'android.test.item_unavailable'],
};
