platform :ios, '9.0'
inhibit_all_warnings!

source 'https://github.com/CocoaPods/Specs.git'

ENV['COCOAPODS_DISABLE_STATS'] = 'true'

target 'Japanese' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  #React Pods
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    # 'BatchedBridge',
    'Core',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
  ]

  # Pods for Japanese
  pod 'Firebase/Core'
  pod 'Firebase/AdMob'
  pod 'Firebase/Analytics'
  pod 'Firebase/Crash'
  pod 'Firebase/Performance'

  pod 'RNFirebase', :path => '../node_modules/react-native-firebase/ios'

  pod 'Fabric'
  pod 'Crashlytics'
  pod 'ReactNativeFabric', :path => '../node_modules/react-native-fabric'

  pod 'GoogleMobileAdsMediationFacebook'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'TextToSpeech', :path => '../node_modules/react-native-tts'

  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'

  pod 'RNI18n', :path => '../node_modules/react-native-i18n'

  pod 'RNStoreReview', :path => '../node_modules/react-native-store-review/ios'

  pod 'OneSignal', '>= 2.8.5', '< 3.0'
  pod 'react-native-onesignal', :path => '../node_modules/react-native-onesignal'

  pod 'RNIap', :path => '../node_modules/react-native-iap'

  pod 'CleverTap-iOS-SDK'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == 'react-native-google-maps'
      target.build_configurations.each do |config|
        config.build_settings['CLANG_ENABLE_MODULES'] = 'No'
      end
    end
    if target.name == 'React'
      target.remove_from_project
    end
  end
end
